# Generated by Django 2.2.4 on 2019-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='description',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
