# Generated by Django 2.2.4 on 2019-08-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectitem',
            options={'ordering': ['upload_date']},
        ),
    ]
