# Generated by Django 2.2.4 on 2019-08-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
