# Generated by Django 2.2.4 on 2019-08-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190812_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectitem',
            options={'ordering': ['-upload_date']},
        ),
    ]
