# Generated by Django 2.2.4 on 2019-08-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='designer_skills',
            field=models.TextField(help_text='Each item of the list splits on two parts:\n {title%content%endtitle}{items%item1;item2;item3;%enditems}'),
        ),
        migrations.AlterField(
            model_name='about',
            name='developer_skills',
            field=models.TextField(help_text='Each item of the list splits on two parts:\n {title%content%endtitle}{items%item1;item2;item3;%enditems}'),
        ),
        migrations.AlterField(
            model_name='about',
            name='education',
            field=models.TextField(help_text='Each item of the article splits on three parts:\n {title%content%endtitle}{years%content%endyears}{text%content%endtext}'),
        ),
        migrations.AlterField(
            model_name='about',
            name='honors',
            field=models.TextField(help_text='Each item of the article splits on three parts:\n {title%content%endtitle}{years%content%endyears}{text%content%endtext}'),
        ),
        migrations.AlterField(
            model_name='about',
            name='work_experience',
            field=models.TextField(help_text='Each item of the article splits on three parts:\n {title%content%endtitle}{years%content%endyears}{text%content%endtext}'),
        ),
    ]
